using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Team1_Workshop4_Part2
{
    public partial class frmAddModifyProduct : Form
    {
        // Darcie Milliken
        public frmAddModifyProduct()
        {
            InitializeComponent();
        }

        public bool addProduct;
        public Product product;

        private void frmAddProduct_Load(object sender, EventArgs e)
        {
            // Run this method when the add product form is loaded
            if (addProduct)
            {
                lblAddModify.Text = "Add a new product";
                this.Text = "Add product";
            }
            else // modify, display current product object name
            {
                lblAddModify.Text = "Modify this product";
                this.Text = "Modify a Product";
                txtProductName.Text = product.ProdName;
            }
        }

        private void btnAccept_Click(object sender, EventArgs e)
        {
            // if there is a product name, try to add it
            if (Validator.IsPresent(txtProductName))
            {
                if (addProduct)
                {
                    product = new Product();
                    // add product name given to the product object
                    product.ProdName = txtProductName.Text;
                    int productID;

                    // try to create the product
                    try
                    {
                        productID = ProductDB.AddProduct(product); // productID is autogenerated
                        this.DialogResult = DialogResult.OK;
                    } // end try
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, ex.GetType().ToString());
                    } // end catch

                } // end if
                else // modify
                {
                    // make a new product object
                    Product newProduct = new Product();
                    newProduct.ProductId = product.ProductId;
                    // put the field text into the new product object 
                    newProduct.ProdName = txtProductName.Text;

                    // try to edit the product 

                    try
                    {
                        if (!ProductDB.UpdateProduct(product, newProduct))
                        {
                            MessageBox.Show("Another user has updated or " +
                                    "deleted that product.", "Database Error");
                            this.DialogResult = DialogResult.Cancel;
                        } // end if
                        else
                        {
                            product = newProduct;
                            this.DialogResult = DialogResult.OK;
                        } // end else
                    } // end try
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, ex.GetType().ToString());
                    } // end catch
                } // end else
            }//end if


        } // end class 
    }
}